nginx:
    build: ./nginx
    ports:
        - "80:80"
    links:
        - go-rest-1:service1
        - go-rest-2:service2
        - go-rest-3:service3
go-rest-1:
  build: .
  links:
   - mongodb:local-mongo
go-rest-2:
  build: .
  links:
   - mongodb:local-mongo
go-rest-3:
  build: .
  links:
   - mongodb:local-mongo
mongodb:
  image: mongo
  ports:
     - "27017:27017"