nginx:
    build: ./nginx
    ports:
        - "80:80"
    links:
        - go-rest-1
        - go-rest-2
        - go-rest-3
go-rest-1:
  build: .
  ports:
   - "8080:8080"
  links:
   - mongodb:local-mongo
go-rest-2:
  build: .
  ports:
   - "8081:8081"
  links:
   - mongodb:local-mongo
go-rest-3:
  build: .
  ports:
   - "8082:8082"
  links:
   - mongodb:local-mongo
mongodb:
  image: mongo
  ports:
     - "27017:27017"